# Generated by Django 3.1.2 on 2021-04-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('petname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('zodiac', models.CharField(default=None, max_length=100)),
                ('hobbies', models.CharField(max_length=100)),
                ('ambition', models.CharField(max_length=100)),
                ('films', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('songs', models.CharField(max_length=100)),
                ('books', models.CharField(max_length=100)),
                ('reality_show', models.CharField(blank=True, max_length=100, null=True)),
                ('singer', models.CharField(max_length=100)),
                ('friends', models.CharField(max_length=100)),
                ('crush', models.CharField(max_length=100)),
                ('fantasy', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
                ('feature', models.CharField(max_length=100)),
                ('lifeline', models.CharField(max_length=100)),
                ('fear', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('lines_for', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
