# Generated by Django 3.1.2 on 2021-04-10 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slam',
            name='name',
        ),
        migrations.AddField(
            model_name='slam',
            name='username',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
