# Generated by Django 3.1.2 on 2021-04-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slam', '0002_auto_20210410_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slam',
            name='movie_role',
        ),
        migrations.AlterField(
            model_name='slam',
            name='birthday',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='slam',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='petname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='slam',
            name='zodiac',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
