# Generated by Django 3.1.2 on 2021-04-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slam', '0004_auto_20210410_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slam',
            name='petname',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
