# Generated by Django 3.1.2 on 2021-04-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slam', '0005_auto_20210410_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slam',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='petname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='reality_show',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
